### ISSUE TITLE
The performance test is unfair with Angular

### ISSUE THREAD

**Issue by nhduc296** [astoilkov/jsblocks#87] opened 2015-09-11 08:21 UTC
You gain a lot of performance when add track by to ng-repeat
```
            <tr ng-repeat="person in people"> // add track by here
               <td ng-repeat="column in columns">// add track by here
                   {{person[column]}}
               </td>
               <td ng-repeat="column in columns">// add track by here
                   {{person[column]}}
               </td>
            </tr>

**Comment by Kanaye** [comment] 2015-09-11 08:53
This is a duplicate of #31.
I think you can close this.

Have a nice day.

**Comment by nhduc296** [comment] 2015-09-11 08:59
@Kanaye thank you

**Closed** 2015-09-13 14:46 UTC
