### ISSUE TITLE
Not synchronize the query 'val' and 'change' into a select box

### ISSUE THREAD

**Issue by froilanq** [astoilkov/jsblocks#80] opened 2015-08-12 16:30 UTC
When he used the queries 'val' and 'change', does not synchronize the value after making the change in the select box.

When you select an option, I selected returns the previous value, would have to return the selected value.

Code sample: http://jsfiddle.net/hjdekjc6/

or 

```html

<div data-query="view(MyView)">
  <p class="log"></p>
  
  <select name="test" id="test" data-query="change(change_event).val(select_input)">
    <option value="">Select</option>
    <option value="One">One</option>
    <option value="Two">Two</option>
    <option value="Three">Three</option>
  </select>
</div>
  
  <script src="https://rawgit.com/astoilkov/jsblocks/master/dist/blocks.js"></script>
  <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
  <script>
    var App = blocks.Application();
    App.View('MyView', {
      init: function(){
          $('.log').append('Init JSBlocks: <br>' );
      },
      select_input: blocks.observable(''),
      change_event: function (e) {
        $('.log').append(this.select_input() + '<br>');
      }
    });   
  </script>

```

**Comment by astoilkov** [comment] 2015-08-13 09:05
The issue is caused because in the select change event the value have not been changed yet You could achieve your scenario by wrapping the change_event code in a setTimeout as shown below:

```html
<div data-query="view(MyView)">
  <p class="log"></p>

  <select name="test" id="test" data-query="change(change_event).val(select_input)">
    <option value="">Select</option>
    <option value="One">One</option>
    <option value="Two">Two</option>
    <option value="Three">Three</option>
  </select>
</div>

  <script src="https://rawgit.com/astoilkov/jsblocks/master/dist/blocks.js"></script>
  <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
  <script>
    var App = blocks.Application();
    App.View('MyView', {
      init: function(){
          $('.log').append('Init JSBlocks: <br>' );
      },
      select_input: blocks.observable(''),
      change_event: function (e) {
        setTimeout(function () {
          $('.log').append(this.select_input() + '<br>');
        }.bind(this));
      }
    });   
  </script>
```

**Comment by froilanq** [comment] 2015-08-13 13:13
Thanks for the solution

**Comment by astoilkov** [comment] 2015-08-16 16:24
Happy to help. Closing this.

**Closed by astoilkov** 2015-08-16 16:24 UTC
Labels: help wanted
