### ISSUE TITLE
data-query set value to options not working in Chrome & Firefox

### ISSUE THREAD

**Issue by atom2ueki** [astoilkov/jsblocks#147] opened 2016-06-07 05:39 UTC
```
<select id="my_id" data-query="options($view.scopeData, { text: 'name', value: 'value', caption: 'Select' }).val($view.test)">
</select>
```
`test` defined in my view 

but it works in Safari

**Comment by Kanaye** [comment] 2016-06-07 06:49
Hey @atom2ueki!

Can you provide more information ?
I'm not able to reproduce your issue.
[This](https://jsfiddle.net/grmsxtu3/) example works in booth Chrome & Firefox.

**Comment by Kanaye** [comment] 2016-07-14 15:40
Hey @atom2ueki,

do you encounter the issue you posted above ?
Or can we close this ?

**Comment by astoilkov** [comment] 2016-07-18 05:50
Closing for now. @atom2ueki - if you still having issues do not hesitate to reopen this issue.

**Closed by astoilkov** 2016-07-18 05:50 UTC
