### ISSUE TITLE
Can't use with jQuery

### ISSUE THREAD

**Issue by clarkeadg** [astoilkov/jsblocks#37] opened 2015-05-29 23:15 UTC
Can this be used with jQuery?

I get this error when I load jQuery on a page with jsblocks.

TypeError: Cannot call method 'createElement' of undefined
   at assert (eval at <anonymous> (c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:11690:23), <anonymous>:15378:21)
   at eval (eval at <anonymous> (c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:11690:23), <anonymous>:17046:24)
   at Config.api.me (eval at <anonymous> (c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:11690:23), <anonymous>:17097:3)
   at arr (eval at <anonymous> (c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:11690:23), <anonymous>:14520:3)
   at eval (eval at <anonymous> (c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:11690:23), <anonymous>:14524:2)
   at c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:11693:19
   at contextBubble (c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:11710:5)
   at executeCode (c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:11683:5)
   at executePageScripts (c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:11678:5)
   at Object.Middleware._renderContents (c:\Users\bclarke\Work\code\factory\src\jsblocks\auth\node_modules\blocks\node\blocks-node.js:12153:9)

**Comment by astoilkov** [comment] 2015-05-29 23:20
The problem is that you are trying to use jQuery on the server. jQuery does not work on the server. The issue is in jQuery not in jsblocks. The error is caused because jQuery assums that it is in the browse and tries to make DOM manipulations.

**Comment by astoilkov** [comment] 2015-05-30 10:02
Hi,

I was thinking about this case and actually there should be a way to skip the execution of libraries that are not supported in Node.js environment. Maybe a attribute on the script tag.

What do you think?

**Comment by clarkeadg** [comment] 2015-05-30 23:17
Hi,

Yes, I think is a good idea.  I am perfectly fine with only using jQuery on the client.  Thank you for answering my question.

A script tag attribute sounds like a great idea to tell a script to only run on the client.

Maybe some like this:

<script data-client-only="true" src="bower_components/jquery/dist/jquery.js"></script>

**Comment by clarkeadg** [comment] 2015-06-01 22:42
I just sent you a pull request that allows client only scripts.

**Comment by astoilkov** [comment] 2015-06-02 06:49
This is awesome. Thanks for that. I am closing this one. I will add this to the documentation soon.

**Closed by astoilkov** 2015-06-02 06:49 UTC
Labels: enhancement, help wanted

**Comment by clarkeadg** [comment] 2015-06-02 07:09
Your welcome, thanks for the awesome framework.  I am having fun with it.
