### ISSUE TITLE
Define views in different instances of time

### ISSUE THREAD

**Issue by froilanq** [astoilkov/jsblocks#131] opened 2016-01-29 23:01 UTC
I have a problem with instantiating views in different periods.
Example:
I have started inicialemte a view ('Search'), and later by Ajax charge: HTML and scripts, which have defined other views and not get an error instance:
TypeError: this._viewPrototypes is undefined.

Could you give me some solution, thanks.

**Comment by Kanaye** [comment] 2016-01-29 23:07
Hey @froilanq!
I have no idea what's causing the problem.
Can you provide a more information?
Maybe an example?
Thanks.

Greetings from Germany

**Comment by froilanq** [comment] 2016-01-29 23:20
This is the code example:
```javascript
$('a.button').click(function(){
	$.get( "get_content", { id: 101}, function(html){
		modal.html(html);
		modal.show();
		App.View('DetailItem', {
			init: function () {

			}
		});
	})
});
```
I click on a button and html load from Ajax, and then instantiate the view within the modal.

**Comment by Kanaye** [comment] 2016-01-29 23:52
First it's not expected to add ``View``s asynchronous to an ``Application`` after the App started.
So blocks internally cleaned up the parts for the initialization and therefore ``App.View`` cannot write to it (and if it could, nothing would happen...).

My question is: 
Why do you need to initialize the View async? 
If you just want to load a template async you could use the Views ``options.url``-property as documented [here](http://jsblocks.com/learn/view-view-lazy-loading).
Also manipulating the DOM of applications can lead to unexpected behavior e.g. when blocks decides to re-render a View.
If you *just* want to use blocks for templating I recommend using ``blocks.query``.

If I'm missing something please correct me.

@astoilkov Should we add the possibility to add View's async or add a debug-message and let ``App.View`` fail if the app is already initialized ?

**Comment by froilanq** [comment] 2016-01-29 23:57
Thanks for the answer, use this and it works:
```javascript
blocks.query({
    var1: 'test',
    var2: 'test2'
}, dom_modal)
```

@astoilkov, greetings from Bolivia.

**Comment by astoilkov** [comment] 2016-02-17 08:15
Hey @Kanaye - I don't think we should make things more complicated with async Views for now. I like the debug-message idea. Do you want me to close this issue or keep it open?

Greetings from Bulgaria @froilanq.

**Comment by Kanaye** [comment] 2016-02-17 19:52
You can close this issue. 
I will keep this in mind and implement it when I implement the message for #116 because I will need to look at the jsdebug code for that first.

**Closed** 2016-02-17 21:09 UTC
